// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  blog: dynamic(() => import("./Blog")),
  careers: dynamic(() => import("./Careers")),
  contact: dynamic(() => import("./Contact")),
  hero: dynamic(() => import("./Hero")),
  image_block: dynamic(() => import("./ImageBlock")),
  privacy_policy: dynamic(() => import("./PrivacyPolicy")),
  text_block: dynamic(() => import("./TextBlock")),
};
