// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  blog: dynamic(() => import("./Blog")),
  contact: dynamic(() => import("./Contact")),
  hero: dynamic(() => import("./Hero")),
  image_block: dynamic(() => import("./ImageBlock")),
  text_block: dynamic(() => import("./TextBlock")),
};
